name: Java Tests

on:
  schedule:
    - cron: 0 */6 * * *
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      # trunk-ignore(checkov/CKV_GHA_7)
      cli-version:
        type: string
        required: false
        description:
          The version of `analytics-cli` to use. Defaults to the latest specified in
          `analytis-uploader`.

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          cache: maven

      - name: Run tests with Gradle
        if: ${{ always() }}
        run: gradle test --project-dir java/gradle


      - name: Run tests with Maven
        if: ${{ always() }}
        run: mvn test --file java/maven/pom.xml --quiet

      - name: Run playwright tests with Maven
        if: ${{ always() }}
        run: mvn test --file java/playwright/pom.xml --quiet
        
      - name: Upload results
        if: "!cancelled()"
        uses: trunk-io/analytics-uploader@main
        with:
          junit-paths: "**/gradle/**/test-results/**/*.xml,**/surefire-reports/*.xml,**/playwright/**/surefire-reports/*.xml"
          org-slug: nix
          token: ${{ secrets.TRUNK_API_TOKEN }}
        continue-on-error: true    
        env:
          TRUNK_PUBLIC_API_ADDRESS: https://api.trunk-staging.io       
