name: Rust Tests

on:
  schedule:
    - cron: 0 */6 * * *
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      # trunk-ignore(checkov/CKV_GHA_7)
      cli-version:
        type: string
        required: false
        description:
          The version of `analytics-cli` to use. Defaults to the latest specified in
          `analytis-uploader`.

jobs:
  test:
    runs-on: ubicloud-standard-2

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@nightly

      - name: Build
        run: cargo build -q --all --manifest-path=./rust/Cargo.toml

      - name: Install nextest
        run: curl -LsSf https://get.nexte.st/latest/linux | tar zxf - -C ${CARGO_HOME:-~/.cargo}/bin

      - name: Run tests
        run: cargo nextest run --profile=ci --manifest-path=./rust/Cargo.toml


      - name: Validate results
        # Run this step even if the test step ahead fails
        if: "!cancelled()"
        run: |
          curl -fsSL --retry 3 "https://github.com/trunk-io/analytics-cli/releases/latest/download/trunk-analytics-cli-x86_64-unknown-linux.tar.gz" | tar -xvz > ./trunk-analytics-cli
          ./trunk-analytics-cli validate --junit-paths "rust/**/nextest/ci/*junit.xml"
          rm ./trunk-analytics-cli          
        continue-on-error: true    

      - name: Upload results
        # Run this step even if the test step ahead fails
        if: "!cancelled()"
        uses: trunk-io/analytics-uploader@main
        with:
          junit-paths: rust/**/nextest/ci/*junit.xml
          org-slug: nix
          token: ${{ secrets.TRUNK_API_TOKEN }}
        continue-on-error: true    
        env:
          TRUNK_PUBLIC_API_ADDRESS: https://api.trunk-staging.io
